version: '3.8'
services:
  postgres:
    image: postgres:13.4-alpine@sha256:3ff2a17bb5bc1f9723032da16edb21e55d2af1e2e0f1beda68818a58ead33016
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_MULTIPLE_DATABASES: app_greeting
    ports:
      - "15432:5432"
    networks:
      - devmode
  pgadmin4:
    image: dpage/pgadmin4:5.7@sha256:64475197fc11cb8169de7e59cd4ea15872b3edafe22f87ea7bc23ba7f00bbe96
    volumes:
      - ./pgadmin4/pgadmin4/servers.json:/pgadmin4/servers.json:ro
    depends_on:
      - postgres
    ports:
      - "8091:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: pgadmin4
    networks:
      - devmode
  greeting:
    image: adoptopenjdk:11.0.11_9-jdk-hotspot-focal@sha256:7ca300be7a4e80848b434994f10d32fedb80a15a845fe87112e64189fbed2abb
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - postgres
    volumes:
      - ./..:/app:rw
    working_dir: /app
    user: ${UID}:${GID}
    environment:
      DB_HOST: postgres:5432
    command:
      - "sh"
      - "-c"
      - "./mvnw -Dmaven.repo.local=/app/.mvn/.m2/repository -DdebugHost=0.0.0.0 -Dquarkus.http.host=0.0.0.0 clean quarkus:dev"
    networks:
      - devmode

networks:
  devmode: